amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: base_link
    odom_frame_id: odom
    map_frame_id: map
    scan_topic: scan

    min_particles: 500
    max_particles: 2000

    resample_interval: 1
    
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
